// Generated by CoffeeScript 1.6.2
(function() {
  var ExtensionContent;

  ExtensionContent = (function() {
    function ExtensionContent() {
      var self,
        _this = this;

      self = this;
      chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
        if (request.action === "actionClicked") {
          self.addRemoveStyleSheet('RR_ColorsCSS');
          return sendResponse({
            message: "ok"
          });
        } else {
          return sendResponse({});
        }
      });
    }

    ExtensionContent.prototype.addRemoveStyleSheet = function(id) {
      var element, link;

      element = document.getElementById(id);
      if (element != null) {
        element.parentElement.removeChild(element);
        return;
      }
      link = document.createElement('link');
      link.rel = 'stylesheet';
      link.type = 'text/css';
      link.href = chrome.extension.getURL('css/debug.css');
      link.id = id;
      return (document.head || document.documentElement).appendChild(link);
    };

    return ExtensionContent;

  })();

  new ExtensionContent;

}).call(this);
